name: Django CD

on:
  workflow_run:
    workflows: 
      - Django CI
    branches:
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Executing Deploy Commands with SSH Connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            git pull
            npm run build-css
            source venv/bin/activate
            python manage.py collectstatic --clear --noinput &> /dev/null
            sudo systemctl restart ${{ secrets.APP_SERVICE }}
